# Generated by Django 5.1.3 on 2024-12-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iso_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classification',
            table='classification',
        ),
        migrations.AlterModelTable(
            name='option',
            table='option',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='userresponse',
            table='user_response',
        ),
    ]
