# Generated by Django 5.1.3 on 2024-12-04 18:23

from django.db import migrations

def add_initial_data(apps, schema_editor):
    # Obtener el modelo Question y la clasificación con ID 1
    Question = apps.get_model('iso_verification', 'Question')
    Classification = apps.get_model('iso_verification', 'Classification')
    classification = Classification.objects.get(id=1)  # Obtener la clasificación con ID 1

    # Crear las preguntas con los datos proporcionados
    questions_data = [
        ("5.1 Políticas de seguridad de la información", "¿La política de seguridad de la información y las políticas específicas del tema son definidas, aprobadas por la gerencia, publicadas, comunicadas y reconocidas por el personal relevante y las partes interesadas relevantes, y revisadas a intervalos planificados y si ocurren cambios significativos?"),
        ("5.2 Roles y responsabilidades de seguridad de la información", "¿Los roles y responsabilidades de seguridad de la información están definidos y asignados de acuerdo con las necesidades de la organización?"),
        ("5.3 Segregación de deberes", "¿Están separados los deberes conflictivos y las áreas conflictivas de responsabilidad?"),
        ("5.4 Responsabilidades de gestión", "¿La gerencia exige a todo el personal que aplique la seguridad de la información de acuerdo con la política de seguridad de la información establecida, las políticas y los procedimientos específicos del tema de la organización?"),
        ("5.5 Contacto con autoridades", "¿La organización ha establecido y mantiene contacto con las autoridades pertinentes?"),
        ("5.6 Contacto con grupos de interés especial", "¿La organización ha establecido y mantiene contacto con grupos de interés especial u otros foros especializados en seguridad y asociaciones profesionales?"),
        ("5.7 Inteligencia de amenazas", "¿Se recopila y analiza la información relacionada con las amenazas a la seguridad de la información para generar información sobre amenazas?"),
        ("5.8 Seguridad de la información en la gestión de proyectos", "¿La seguridad de la información está integrada en la gestión de proyectos?"),
        ("5.9 Inventario de información y otros activos asociados", "¿Se ha desarrollado y se mantiene un inventario de información y otros activos asociados, incluidos los propietarios?"),
        ("5.10 Uso aceptable de la información y otros activos asociados", "¿Se han identificado, documentado e implementado reglas para el uso aceptable y procedimientos para el manejo de la información y otros activos asociados?"),
        ("5.11 Devolución de activos", "¿El personal y otras partes interesadas, según corresponda, devuelven todos los activos de la organización que están en su poder al cambiar o terminar su empleo, contrato o acuerdo?"),
        ("5.12 Clasificación de la información", "¿La información se clasifica de acuerdo con las necesidades de seguridad de la información de la organización en función de la confidencialidad, la integridad, la disponibilidad y los requisitos pertinentes de las partes interesadas?"),
        ("5.13 Etiquetado de información", "¿Se ha desarrollado e implementado un conjunto apropiado de procedimientos para el etiquetado de la información de acuerdo con el esquema de clasificación de la información adoptado por la organización?"),
        ("5.14 Transferencia de información", "¿Existen reglas, procedimientos o acuerdos de transferencia de información para todos los tipos de instalaciones de transferencia dentro de la organización y entre la organización y otras partes?"),
        ("5.15 Control de acceso", "¿Las reglas para controlar el acceso físico y lógico a la información y otros activos asociados se han establecido e implementado en función de los requisitos de seguridad de la información y del negocio?"),
        ("5.16 Gestión de identidad", "¿Se gestiona el ciclo de vida completo de las identidades?"),
        ("5.17 Información de autenticación", "¿La asignación y gestión de la información de autenticación se controla mediante un proceso de gestión, incluido el asesoramiento al personal sobre el manejo adecuado de la información de autenticación?"),
        ("5.18 Derechos de acceso", "¿Los derechos de acceso a la información y otros activos asociados se proporcionan, revisan, modifican y eliminan de acuerdo con la política y las reglas de control de acceso específicas del tema de la organización?"),
        ("5.19 Seguridad de la información en las relaciones con los proveedores", "¿Se han definido e implementado procesos y procedimientos para gestionar los riesgos de seguridad de la información asociados con el uso de los productos o servicios del proveedor?"),
        ("5.20 Abordar la seguridad de la información en los acuerdos con los proveedores", "¿Los requisitos de seguridad de la información pertinentes se han establecido y acordado con cada proveedor en función del tipo de relación con el proveedor?"),
        ("5.21 Gestión de la seguridad de la información en la cadena de suministro de TIC", "¿Se han definido e implementado procesos y procedimientos para gestionar los riesgos de seguridad de la información asociados con la cadena de suministro de productos y servicios de TIC?"),
        ("5.22 Seguimiento, revisión y gestión de cambios de servicios de proveedores", "¿La organización monitorea, revisa, evalúa y gestiona periódicamente los cambios en las prácticas de seguridad de la información del proveedor y la prestación de servicios?"),
        ("5.23 Seguridad de la información para el uso de servicios en la nube", "¿Los procesos de adquisición, uso, gestión y salida de los servicios en la nube se han establecido de acuerdo con los requisitos de seguridad de la información de la organización?"),
        ("5.24 Planificación y preparación de la gestión de incidentes", "¿La organización ha planificado y se ha preparado para la gestión de incidentes de seguridad de la información definiendo, estableciendo y comunicando procesos, roles y responsabilidades de gestión de incidentes?"),
        ("5.25 Evaluación y decisión sobre eventos de seguridad", "¿La organización evalúa los eventos de seguridad de la información y decide si se clasificarán como incidentes de seguridad de la información?"),
        ("5.26 Respuesta a incidentes de seguridad", "¿Se responde a los incidentes de seguridad de la información de acuerdo con los procedimientos documentados?"),
        ("5.27 Aprender de los incidentes", "¿El conocimiento obtenido de los incidentes de seguridad de la información se utiliza para fortalecer y mejorar los controles de seguridad de la información?"),
        ("5.28 Recolección de evidencia", "¿La organización ha establecido e implementado procedimientos para la identificación, recolección, adquisición y preservación de evidencia relacionada con eventos de seguridad de la información?"),
        ("5.29 Seguridad de la información durante la interrupción", "¿La organización ha planificado cómo mantener la seguridad de la información en un nivel adecuado durante la interrupción?"),
        ("5.30 Preparación de las TIC para la continuidad del negocio", "¿La preparación de las TIC se ha planificado, implementado, mantenido y probado en función de los objetivos de continuidad del negocio y los requisitos de continuidad de las TIC?"),
        ("5.31 Requisitos legales, estatutarios, reglamentarios y contractuales", "¿Los requisitos legales, estatutarios, reglamentarios y contractuales relevantes para la seguridad de la información y el enfoque de la organización para cumplir con estos requisitos se han identificado, documentado y se mantienen actualizados?"),
        ("5.32 Derechos de propiedad intelectual", "¿La organización ha implementado procedimientos apropiados para proteger los derechos de propiedad intelectual?"),
        ("5.33 Protección de registros", "¿Los registros están protegidos contra pérdida, destrucción, falsificación, acceso no autorizado y publicación no autorizada?"),
        ("5.34 Privacidad y protección de PII", "¿La organización ha identificado y cumple los requisitos relacionados con la preservación de la privacidad y la protección de la PII de acuerdo con las leyes, reglamentos y requisitos contractuales aplicables?"),
        ("5.35 Revisión independiente de la seguridad", "¿El enfoque de la organización para gestionar la seguridad de la información y su implementación se revisa de forma independiente a intervalos planificados o cuando se producen cambios significativos?"),
        ("5.36 Cumplimiento de políticas y estándares", "¿El cumplimiento de la política de seguridad de la información de la organización, las políticas, las reglas y los estándares específicos de cada tema se revisa periódicamente?"),
        ("5.37 Procedimientos operativos documentados", "¿Los procedimientos operativos para las instalaciones de procesamiento de información están documentados y puestos a disposición del personal que los necesita?")
    ]

    # Insertar cada pregunta con el topic y texto correspondiente
    for topic, text in questions_data:
        Question.objects.create(
            text=text,
            classification=classification,
            topic=topic
        )


class Migration(migrations.Migration):

    dependencies = [
        ('iso_verification', '0002_alter_classification_table_alter_option_table_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
