# Generated by Django 5.1.3 on 2024-12-04 21:57

from django.db import migrations

def add_additional_data(apps, schema_editor):
    # Obtener el modelo Question y la clasificación con ID 6
    Question = apps.get_model('iso_verification', 'Question')
    Classification = apps.get_model('iso_verification', 'Classification')
    classification = Classification.objects.get(id=2)  # Obtener la clasificación con ID 6

    # Crear las preguntas con los datos proporcionados
    questions_data = [
        ("6.1 Poner en pantalla", "¿Los controles de verificación de antecedentes de todos los candidatos para convertirse en personal se llevan a cabo antes de unirse a la organización y de manera continua, teniendo en cuenta las leyes, reglamentos y ética aplicables, y son proporcionales a los requisitos comerciales, la clasificación de la información a la que se accederá y los riesgos percibidos?"),
        ("6.2 Términos y condiciones de empleo", "¿Los acuerdos contractuales de trabajo establecen las responsabilidades del personal y de la organización en materia de seguridad de la información?"),
        ("6.3 Concientización, educación y capacitación", "¿El personal de la organización y las partes interesadas relevantes reciben la concientización, educación y capacitación adecuadas en seguridad de la información y actualizaciones periódicas de la política de seguridad de la información, las políticas y los procedimientos específicos del tema, según sea relevante para su función laboral?"),
        ("6.4 Proceso Disciplinario", "¿Se ha formalizado y comunicado un proceso disciplinario para tomar acciones contra el personal y otras partes interesadas relevantes que hayan cometido una violación a la política de seguridad de la información?"),
        ("6.5 Responsabilidades después de la terminación o cambio de empleo", "¿Las responsabilidades y deberes de seguridad de la información que siguen siendo válidos después de la terminación o el cambio de empleo se han definido, aplicado y comunicado al personal pertinente y otras partes interesadas?"),
        ("6.6 Acuerdos de confidencialidad o no divulgación", "¿Los acuerdos de confidencialidad o no divulgación que reflejan las necesidades de la organización para la protección de la información han sido identificados, documentados, revisados regularmente y firmados por el personal y otras partes interesadas relevantes?"),
        ("6.7 Trabajo remoto", "¿Se han implementado medidas de seguridad cuando el personal trabaja de forma remota para proteger la información a la que se accede, procesa o almacena fuera de las instalaciones de la organización?"),
        ("6.8 Informes de eventos de seguridad de la información", "¿La organización proporciona un mecanismo para que el personal informe eventos de seguridad de la información observados o sospechados a través de los canales apropiados de manera oportuna?"),
    ]

    # Crear las preguntas y asignarles la clasificación
    for topic, text in questions_data:
        Question.objects.create(
            text=text,
            classification=classification,
            topic=topic
        )

class Migration(migrations.Migration):

    dependencies = [
        ('iso_verification', '0006_remove_session_is_active_alter_session_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.RunPython(add_additional_data),
    ]
